### ISSUE TITLE
Future supported architectures?

### ISSUE THREAD

**Issue by sten0** [WuBingzheng/memleax#32]
Hi!

Thank you for creating memleax.  I've packaged it for Debian :-)  https://packages.debian.org/sid/main/memleax

I'd also be happy to enable continuous integration using autopkgtest ( https://ci.debian.net/ ) if there are any self-tests that you'd like to run.

Finally, would you please let me know what architectures will not be supported in the future so that I can disable them?  I think that it would be best to leave the ones for which support is planned enabled and let them fail (for now) on the Debian build servers, but I should explicitly disable support for the definitely unsupported ones.

The ones I'm not sure about these primary architectures: mips, mips64el, mipsel, powerpc, ppc64el, and s390x.  There are more here https://buildd.debian.org/status/package.php?p=memleax&suite=unstable but they're secondary archs.

Sincerely,
Nicholas

P.S. if you're interested, here is the page for the requalification status for all primary archs for the next stable version. (Debian 10 aka "buster") https://release.debian.org/buster/arch_qualify.html

**Comment by WuBingzheng** [comment]
Thanks for packaging memleax for Debian.

I have no plan to support new architectures, because I have no these develop environment and there seems no need.
But if there is anyone asks for it and I happens to get this architecture develop environment, I am very happy to add them into support.
So I am sorry I could not give you a clear answer.

There is no self-test now. If I add some, I will let you know.

By the way, I just find and fix a bug in memleax, and I will release a new version days later. I will notice you then.

Thanks again

**Comment by sten0** [comment]
Hi WuBingzheng,

You're welcome :-) Thank you for the quick reply, and for clearing
this up.  I've disabled build attempts for unsupported architectures,
and would be happy to re-enable them if ever there emerges a need for
them.

By the way, if ever access to hardware is the issue, I wonder if
someone on a team like this one would know what resources are
available: https://www.debian.org/ports/s390/

Looking forward to the upcoming bugfix release,
Thank you,
Nicholas

**Comment by WuBingzheng** [comment]
I have released the new version v1.1.1.
